# Generated by Django 3.1.6 on 2021-02-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('voice_text', models.CharField(default='', max_length=500, unique=True)),
                ('file_name', models.CharField(default='', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_file', models.BooleanField(default=1)),
                ('text', models.CharField(default='', max_length=500, unique=True)),
            ],
        ),
    ]
